from  turtle import Turtle,Screen
tim=Turtle()
tim.shape("turtle")
tim.color("chartreuse4")
tim.forward(300)
tim.left(90)
tim.forward(100)
tim.left(90)
tim.forward(300)
tim.left(90)
tim.forward(100)
print(tim)
scr=Screen()
print(scr.canvheight)
scr.exitonclick()
